#!/usr/bin/env python3
"""
Generate PostgreSQL upsert SQL for one daily candle date from Kiwoom REST OpenAPI.

The script calls Kiwoom ka10081, renders SQL, and does not write to the DB.

Target codes can come from:
  1. --codes / --codes-file
  2. DATABASE_URL: listed stocks missing the target candle date

Required env, unless KIWOOM_ACCESS_TOKEN is provided:
  KIWOOM_APP_KEY
  KIWOOM_APP_SECRET

Optional env:
  DATABASE_URL
  KIWOOM_ACCESS_TOKEN
  KIWOOM_BASE_URL=https://api.kiwoom.com
  KIWOOM_TOKEN_PATH=/oauth2/token
  KIWOOM_CHART_PATH=/api/dostk/chart

Example:
  python3 scripts/generate_daily_candles_sql_from_kiwoom.py \\
    --date 2026-07-08 \\
    --codes-file missing_codes.txt \\
    --output sql/daily_candles_20260708.sql
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import date
from pathlib import Path
from typing import Any, Iterable, Sequence

from migrate_daily_candles_from_kiwoom import (
    DEFAULT_BASE_URL,
    DEFAULT_CHART_PATH,
    DEFAULT_DATABASE_URL,
    DEFAULT_TOKEN_PATH,
    DailyCandle,
    KiwoomChartClient,
    clean_code,
    fetch_target_codes,
    load_db_module,
)


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_bool(value: bool) -> str:
    return "true" if value else "false"


def render_sql(candles: Sequence[DailyCandle], business_date: date, update_stock_close: bool, batch_size: int) -> str:
    lines: list[str] = [
        f"-- Generated by scripts/generate_daily_candles_sql_from_kiwoom.py",
        f"-- Kiwoom ka10081 daily candles for business_date={business_date.isoformat()}",
        "-- Run with search_path including stock schema, e.g. stock,public.",
        "\\set ON_ERROR_STOP on",
        "",
        "BEGIN;",
        "",
    ]

    if not candles:
        lines.extend(
            [
                "-- No candles fetched.",
                "COMMIT;",
                "",
            ]
        )
        return "\n".join(lines)

    for batch in chunks(candles, batch_size):
        values = []
        for candle in batch:
            values.append(
                "    ("
                f"{sql_literal(candle.code)}, "
                "'1d', "
                f"{sql_literal(candle.open_time.isoformat())}::timestamptz, "
                f"{candle.open}, {candle.high}, {candle.low}, {candle.close}, {candle.volume}, "
                f"{sql_bool(True)}, 'KIWOOM', now()"
                ")"
            )

        lines.extend(
            [
                "INSERT INTO candles (",
                "    stock_code, interval, open_time, open, high, low, close, volume, closed, source, updated_at",
                ")",
                "VALUES",
                ",\n".join(values),
                "ON CONFLICT (stock_code, interval, open_time) DO UPDATE SET",
                "    open = EXCLUDED.open,",
                "    high = EXCLUDED.high,",
                "    low = EXCLUDED.low,",
                "    close = EXCLUDED.close,",
                "    volume = EXCLUDED.volume,",
                "    closed = EXCLUDED.closed,",
                "    source = EXCLUDED.source,",
                "    updated_at = now();",
                "",
            ]
        )

    if update_stock_close:
        lines.extend(
            [
                "CREATE TEMP TABLE tmp_generated_daily_close (",
                "    stock_code varchar(6) PRIMARY KEY,",
                "    close_price bigint NOT NULL",
                ") ON COMMIT DROP;",
                "",
            ]
        )
        for batch in chunks(candles, batch_size):
            values = [f"    ({sql_literal(c.code)}, {c.close})" for c in batch]
            lines.extend(
                [
                    "INSERT INTO tmp_generated_daily_close (stock_code, close_price)",
                    "VALUES",
                    ",\n".join(values),
                    "ON CONFLICT (stock_code) DO UPDATE SET",
                    "    close_price = EXCLUDED.close_price;",
                    "",
                ]
            )
        lines.extend(
            [
                "UPDATE stocks s",
                "SET close_price = p.close_price,",
                "    data_source = 'KIWOOM',",
                "    synced_at = now(),",
                "    updated_at = now()",
                "FROM tmp_generated_daily_close p",
                "WHERE s.stock_code = p.stock_code",
                "  AND s.close_price IS DISTINCT FROM p.close_price;",
                "",
            ]
        )

    lines.extend(
        [
            "COMMIT;",
            "",
            f"-- fetched_candles={len(candles)}",
        ]
    )
    return "\n".join(lines)


def parse_codes(raw: str | None) -> list[str]:
    if not raw:
        return []
    seen: set[str] = set()
    codes: list[str] = []
    for part in re.split(r"[\s,]+", raw):
        if not part:
            continue
        code = clean_code(part)
        if code and code not in seen:
            seen.add(code)
            codes.append(code)
    return codes


def load_codes_file(path: str | None) -> list[str]:
    if not path:
        return []
    return parse_codes(Path(path).read_text(encoding="utf-8"))


def load_target_codes(args: argparse.Namespace, business_date: date) -> list[str]:
    explicit = parse_codes(args.codes) + load_codes_file(args.codes_file)
    if explicit:
        seen: set[str] = set()
        return [code for code in explicit if not (code in seen or seen.add(code))]

    database_url = args.database_url or os.getenv("DATABASE_URL")
    if not database_url:
        raise RuntimeError("Provide --codes/--codes-file or set DATABASE_URL to select target stocks")

    db = load_db_module()
    with db.connect(database_url) as conn:
        return fetch_target_codes(conn, business_date, args.include_existing, args.limit)


def chunks(items: Sequence[Any], size: int) -> Iterable[Sequence[Any]]:
    for index in range(0, len(items), size):
        yield items[index : index + size]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate daily candle upsert SQL from Kiwoom ka10081.")
    parser.add_argument("--date", required=True, help="Business date, YYYY-MM-DD.")
    parser.add_argument("--output", required=True, help="SQL output path. Use '-' for stdout.")
    parser.add_argument("--codes", help="Comma/space-separated stock codes.")
    parser.add_argument("--codes-file", help="File containing comma/space/newline-separated stock codes.")
    parser.add_argument("--database-url", default=os.getenv("DATABASE_URL", DEFAULT_DATABASE_URL))
    parser.add_argument("--include-existing", action="store_true", help="When selecting from DB, include stocks that already have the candle.")
    parser.add_argument("--limit", type=int, help="Limit target code count.")
    parser.add_argument("--sleep", type=float, default=0.25, help="Sleep seconds between Kiwoom requests.")
    parser.add_argument("--timeout", type=float, default=30.0)
    parser.add_argument("--sql-batch-size", type=int, default=500, help="Rows per SQL INSERT statement.")
    parser.add_argument("--no-stock-close-update", action="store_true", help="Do not render stocks.close_price update SQL.")
    parser.add_argument("--base-url", default=os.getenv("KIWOOM_BASE_URL", DEFAULT_BASE_URL))
    parser.add_argument("--token-path", default=os.getenv("KIWOOM_TOKEN_PATH", DEFAULT_TOKEN_PATH))
    parser.add_argument("--chart-path", default=os.getenv("KIWOOM_CHART_PATH", DEFAULT_CHART_PATH))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    business_date = date.fromisoformat(args.date)
    if args.sql_batch_size < 1:
        print("--sql-batch-size must be greater than 0", file=sys.stderr)
        return 2

    codes = load_target_codes(args, business_date)
    if args.limit and (args.codes or args.codes_file):
        codes = codes[: args.limit]
    print(f"target_date={business_date} target_codes={len(codes)}", file=sys.stderr)

    client = KiwoomChartClient(
        base_url=args.base_url,
        token_path=args.token_path,
        chart_path=args.chart_path,
        timeout=args.timeout,
        sleep_seconds=args.sleep,
        app_key=os.getenv("KIWOOM_APP_KEY"),
        app_secret=os.getenv("KIWOOM_APP_SECRET"),
        access_token=os.getenv("KIWOOM_ACCESS_TOKEN"),
    )

    candles: list[DailyCandle] = []
    empty = 0
    failed = 0
    for index, code in enumerate(codes, start=1):
        try:
            candle = client.fetch_daily_candle(code, business_date)
            if candle is None:
                empty += 1
            else:
                candles.append(candle)
        except Exception as exc:
            failed += 1
            print(f"failed code={code}: {exc}", file=sys.stderr)

        if index % 50 == 0:
            print(f"progress requested={index}/{len(codes)} fetched={len(candles)} empty={empty} failed={failed}", file=sys.stderr)

    sql = render_sql(
        candles,
        business_date,
        update_stock_close=not args.no_stock_close_update,
        batch_size=args.sql_batch_size,
    )
    if args.output == "-":
        print(sql)
    else:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(sql, encoding="utf-8")
        print(f"wrote {output}", file=sys.stderr)

    print(f"done target_codes={len(codes)} fetched={len(candles)} empty={empty} failed={failed}", file=sys.stderr)
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
