-- Generated by naver_news_batch.py — stocks=5 max/stock=5 sort=date

-- Generated by naver_news_fetch.py
-- query='동화약품'  count=5  generated_at=2026-07-08T21:52:15.309047+00:00
BEGIN;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '동화약품 노사, 화합 선언문 발표…"고객가치 위해 상생·화합"',
    '동화약품 노사가 ''노사화합 선언문''을 발표한 후 기념사진을 촬영하고 있다. |동화약품 동화약품과 동화약품 노동조합은 노사 간 상호 신뢰와 협력을 강화하고 지속 가능한 성장을 추진하기 위한 ''노사화합 선언문''을...',
    'http://www.biztribune.co.kr/news/articleView.html?idxno=355682',
    'biztribune.co.kr',
    TIMESTAMPTZ '2026-07-08T21:32:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000020', '동화약품' FROM news.articles a WHERE a.url = 'http://www.biztribune.co.kr/news/articleView.html?idxno=355682'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '상장 제약·바이오 1Q 평균 ROE 코스피 1.95%·코스닥 0.19%',
    '주요 상승 기업들의 순위와 증감%p를 살펴보면 1위 에이프로젠바이오로직스(+9.30%p), 2위 SK바이오팜(+7.24%p), 3위 보령(+4.89%p), 4위 일동제약(+3.47%p), 5위 동화약품(+2.62%p), 6위 동아에스티(+2.56%p), 7위...',
    'https://www.yakup.com/news/index.html?mode=view&cat=12&nid=329579',
    'yakup.com',
    TIMESTAMPTZ '2026-07-08T21:02:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000020', '동화약품' FROM news.articles a WHERE a.url = 'https://www.yakup.com/news/index.html?mode=view&cat=12&nid=329579'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '빅10 토종제약사들, 아태지역 영토 확장...외자사 아성 넘본다',
    '동화약품은 베트남의 대형 약국 체인 ''중선파마'' 인수를 통해 유통망 자체를 확보하며 수출을 넘어선 판매 구조 장악에 나섰다. ''활명수'', ''판콜'', ''잇치'' 등 국내 브랜드 인지도가 높은 일반의약품(OTC)을 현지 약국 채널에...',
    'https://www.pharmnews.com/news/articleView.html?idxno=304772',
    'pharmnews.com',
    TIMESTAMPTZ '2026-07-08T21:00:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000020', '동화약품' FROM news.articles a WHERE a.url = 'https://www.pharmnews.com/news/articleView.html?idxno=304772'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '[헬스 이모저모] 동화약품, 세라젬, 파마리서치메디케어 등',
    '동화약품 노사가 지난 6일 ''노사화합 선언문''을 발표한 후 기념사진을 촬영하고 있다. 사진=동화약품 ◆동화약품 노사, 화합 선언문 발표 동화약품(대표 윤인호·유준하)이 상생 중심의 노사문화를 바탕으로 미래 성장동력...',
    'http://www.bizwnews.com/news/articleView.html?idxno=140207',
    'bizwnews.com',
    TIMESTAMPTZ '2026-07-08T10:30:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000020', '동화약품' FROM news.articles a WHERE a.url = 'http://www.bizwnews.com/news/articleView.html?idxno=140207'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '동화약품, 노사화합 선언문 발표…"회사·직원 함께 성장"',
    '동화약품은 회사 노동조합과 상호 신뢰와 협력을 강화하고 지속 가능한 성장을 추진하기 위해 ''노사화합 선언문''을 8일 발표했다. 노사화합 선언은 고객 가치를 최우선 과제로 삼고 신뢰와 배려, 소통으로 변화와 혁신을...',
    'https://www.dt.co.kr/article/12071902?ref=naver',
    'dt.co.kr',
    TIMESTAMPTZ '2026-07-08T08:40:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000020', '동화약품' FROM news.articles a WHERE a.url = 'https://www.dt.co.kr/article/12071902?ref=naver'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

COMMIT;

-- Generated by naver_news_fetch.py
-- query='KR모터스'  count=5  generated_at=2026-07-08T21:52:15.704670+00:00
BEGIN;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    'LG엔솔-GM 합작 얼티엄셀즈, ESS용 LFP셀 양산 시작',
    'LG에너지솔루션과 제너럴모터스(GM)의 합작사인 얼티엄셀즈가 미국 테네시주 스프링힐 공장에서... 부당대우, 사건사고와 미담 등 모든 얘깃거리를 알려주세요.이메일 : 카카오톡 : @노컷뉴스사이트 : https://url.kr/b71afn',
    'https://www.nocutnews.co.kr/news/6544998?utm_source=naver&utm_medium=article&utm_campaign=20260708022610',
    'nocutnews.co.kr',
    TIMESTAMPTZ '2026-07-08T05:27:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000040', 'KR모터스' FROM news.articles a WHERE a.url = 'https://www.nocutnews.co.kr/news/6544998?utm_source=naver&utm_medium=article&utm_campaign=20260708022610'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '종합특검, ''김건희 의혹'' 유경옥·이원모 소환',
    '특검팀은 또 김씨의 도이치모터스 주가조작 사건을 수사한 검찰이 김씨를 청사로 불러 조사하는 대신 제3의... 사건사고와 미담 등 모든 얘깃거리를 알려주세요.이메일 : 카카오톡 : @노컷뉴스사이트 : https://url.kr/b71afn',
    'https://www.nocutnews.co.kr/news/6544151?utm_source=naver&utm_medium=article&utm_campaign=20260707104656',
    'nocutnews.co.kr',
    TIMESTAMPTZ '2026-07-07T01:47:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000040', 'KR모터스' FROM news.articles a WHERE a.url = 'https://www.nocutnews.co.kr/news/6544151?utm_source=naver&utm_medium=article&utm_campaign=20260707104656'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '훈장 받았는데…종합특검 "조성현이 국회 진입 지시했다는 진술 확보"',
    '특검은 이원모 전 비서관이 김건희 씨가 도이치모터스 주가조작 사건으로 수사를 받을 당시, 제3의 장소에서... 사건사고와 미담 등 모든 얘깃거리를 알려주세요.이메일 : 카카오톡 : @노컷뉴스사이트 : https://url.kr/b71afn',
    'https://www.nocutnews.co.kr/news/6543698?utm_source=naver&utm_medium=article&utm_campaign=20260706034546',
    'nocutnews.co.kr',
    TIMESTAMPTZ '2026-07-06T06:46:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000040', 'KR모터스' FROM news.articles a WHERE a.url = 'https://www.nocutnews.co.kr/news/6543698?utm_source=naver&utm_medium=article&utm_campaign=20260706034546'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '[유통갤러리] 롯데하이마트, 부동산 거래부터 가전 구매까지 ‘원스톱’...',
    '뷰어스 전지현 기­자 gee7871@viewers.co.kr ◆롯데하이마트, 부동산 거래부터 가전 구매까지 ‘원스톱 시스템’... ◆쿠팡, 여름맞이 쿠팡모터스 페어 진행…40여개 인기 차량용품 브랜드 할인 쿠팡이 본격적인 여름...',
    'https://theviewers.co.kr/View.aspx?No=4135784',
    'theviewers.co.kr',
    TIMESTAMPTZ '2026-07-03T01:20:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000040', 'KR모터스' FROM news.articles a WHERE a.url = 'https://theviewers.co.kr/View.aspx?No=4135784'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '[공식발표] 전북, 제주 출신 리투아니아 국대 FW 기티스 임대 영입...최...',
    '기티스는 메디컬 테스트를 마친 뒤 곧바로 팀 훈련에 합류했다. 전북은 기티스 영입을 시작으로 후반기 전력 강화를 위한 추가 보강 작업도 이어간다는 계획이다. /reccos23@osen.co.kr [사진] 전북현대모터스 FC 제공',
    'http://www.osen.co.kr/article/G1112832497',
    'osen.co.kr',
    TIMESTAMPTZ '2026-07-02T04:23:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000040', 'KR모터스' FROM news.articles a WHERE a.url = 'http://www.osen.co.kr/article/G1112832497'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

COMMIT;

-- Generated by naver_news_fetch.py
-- query='경방'  count=5  generated_at=2026-07-08T21:52:16.098504+00:00
BEGIN;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '패션·섬유주, 전반적 약세 지속…뷰티주 혼조세',
    '휴비스(-0.79%), 경방(-1.45%), 일신방직(-3.21%), 방림(-1.89%), 티케이케미칼(-1.59%), 신라섬유(-6.95%), 경인양행(-4.47%) 등도 하락했다. 반면 대한방직(+0.87%), 대한화섬(+1.23%), 우성머티리얼즈(+3.36%), 일정실업(+0.62%), 대동...',
    'http://okfashion.co.kr/detail.php?number=63811&thread=62r04',
    'okfashion.co.kr',
    TIMESTAMPTZ '2026-07-08T12:56:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000050', '경방' FROM news.articles a WHERE a.url = 'http://okfashion.co.kr/detail.php?number=63811&thread=62r04'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '“영등포 호재 놓칠 수 없지”…백화점들, 성적표 엇갈린 이유가 [현장...',
    '도보 5분 거리에 있는 신세계백화점 타임스퀘어점과 경방 타임스퀘어, 여기에 더현대 서울까지 가세하면서... 신세계백화점 타임스퀘어점과 경방 타임스퀘어의 지난해 합산 매출은 1조3000억원을 기록했다. 개점 이후...',
    'https://www.mk.co.kr/article/12093719',
    'mk.co.kr',
    TIMESTAMPTZ '2026-07-08T09:05:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000050', '경방' FROM news.articles a WHERE a.url = 'https://www.mk.co.kr/article/12093719'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '패션·섬유·뷰티주, 업종별 희비 교차…뷰티 강세, 섬유 약세',
    '다만 휴비스는 0.91% 상승하며 선방했고, 대한방직(+1.41%), 대한방직(+3.56%), 경방(+0.61%), 우성머티리얼즈(+1.59%), 경인양행(+4.71%) 등 일부 종목은 상승 흐름을 보였다. 반면 일신방직(-12.34%), 신라섬유(-12.94%) 등은...',
    'http://okfashion.co.kr/detail.php?number=63803&thread=62r04',
    'okfashion.co.kr',
    TIMESTAMPTZ '2026-07-07T07:18:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000050', '경방' FROM news.articles a WHERE a.url = 'http://okfashion.co.kr/detail.php?number=63803&thread=62r04'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '김좌진 마더스제약 대표의 핵심 진용…IPO 조직 경쟁력 완성',
    '익산공장을 총괄하는 박용수 부사장은 다산제약과 근화제약 등을 거친 약사 출신이며, 전병진 상무는 신신제약과 경방신약에서 품질관리와 생산을 담당했다. 경산공장을 맡고 있는 이갑진 상무는 코오롱제약과...',
    'https://www.dailypharm.com/user/news/340170?REFERER=NP',
    'dailypharm.com',
    TIMESTAMPTZ '2026-07-06T21:02:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000050', '경방' FROM news.articles a WHERE a.url = 'https://www.dailypharm.com/user/news/340170?REFERER=NP'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '원료 칭량 후 부적합 장소 보관…경방신약, 2개 품목 제조업무정지',
    '경방신약이 제조관리기준서 등 제조지시 및 기록서 관리 기준을 준수하지 않은 사실이 확인되면서... 6일 의약품안전나라 등에 따르면 식약처는 최근 경방신약의 ''쎄파렉신캡슐(은교산)''과 ''소폐탕엑스과립(소청룡탕)''에...',
    'https://www.kpanews.co.kr/news/articleView.html?idxno=538109',
    'kpanews.co.kr',
    TIMESTAMPTZ '2026-07-06T20:56:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000050', '경방' FROM news.articles a WHERE a.url = 'https://www.kpanews.co.kr/news/articleView.html?idxno=538109'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

COMMIT;

-- Generated by naver_news_fetch.py
-- query='삼양홀딩스'  count=5  generated_at=2026-07-08T21:52:16.497600+00:00
BEGIN;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '공정위, 전분당 담합 4개 업체 역대 최대 7476억 과징금 부과',
    '삼양홀딩스 측은 "고객과 소비자 여러분께 심려를 끼쳐드린 점 깊이 사과드린다"며 "회사는 그동안 시장 관행과 거래 환경 속에서 발생할 수 있는 법적 리스크를 보다 엄격하게 관리하지 못한 부분이 있었다는 점을...',
    'https://www.mdtoday.co.kr/news/articleView.html?idxno=603983',
    'mdtoday.co.kr',
    TIMESTAMPTZ '2026-07-07T09:46:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000070', '삼양홀딩스' FROM news.articles a WHERE a.url = 'https://www.mdtoday.co.kr/news/articleView.html?idxno=603983'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '''수출 넘어 현지로''…일본서 판 키우는 식품업계',
    '삼양홀딩스 본사. 사진=삼양그룹 제공 삼양사는 일본 5대 향료기업인 소다 아로마틱(Soda Aromatic) 인수를 통해 스페셜티 식품소재 사업을 강화한다. 일본 법인을 통해 도레이와 미쓰이물산이 보유한 소다 아로마틱 지분 100...',
    'https://daily.hankooki.com/news/articleView.html?idxno=1383179',
    'daily.hankooki.com',
    TIMESTAMPTZ '2026-07-07T05:52:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000070', '삼양홀딩스' FROM news.articles a WHERE a.url = 'https://daily.hankooki.com/news/articleView.html?idxno=1383179'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '환율 하락 수혜주 급등…내수·항공·식품 전방위 신바람',
    '식품 업종에서는 하이트진로, 오뚜기, 대상, 삼양홀딩스 등이 동반 강세를 보이며 원가 부담 완화 기대가 확산되고 있다. 특히 곡물 수입 비중이 높은 기업일수록 환율 효과가 즉각적으로 반영되는 구조다. 철강 및 소재...',
    'https://www.pinpointnews.co.kr/news/articleView.html?idxno=464961',
    'pinpointnews.co.kr',
    TIMESTAMPTZ '2026-07-02T01:44:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000070', '삼양홀딩스' FROM news.articles a WHERE a.url = 'https://www.pinpointnews.co.kr/news/articleView.html?idxno=464961'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '[ESG 공시 릴레이①] ''지속가능경영보고서'' 공개 잇따라... 탄소중립·미...',
    '이번 보고서는 △삼양홀딩스 △삼양사 △삼양바이오팜 △삼양패키징 △삼양케이씨아이 등 그룹 내 상장 5개사의 ESG 경영 활동과 성과를 통합해 수록했다. 특히 지난해 독립법인으로 출범한 삼양바이오팜이...',
    'https://www.banronbodo.com/news/articleView.html?idxno=32551',
    'banronbodo.com',
    TIMESTAMPTZ '2026-06-30T23:00:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000070', '삼양홀딩스' FROM news.articles a WHERE a.url = 'https://www.banronbodo.com/news/articleView.html?idxno=32551'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '[K백년기업]삼양그룹① 福·氣·財 세 가지를 기른 것은 친일?···창업...',
    '2011년 삼양사는 지주사 (주)삼양홀딩스와 (주)삼양사로 분할됐다. 김연수는 일제강점기와 해방 후 산업화의 기반을 닦은 기업인으로 평가받는 동시에 일제의 식민통치와 침략전쟁에 협력한 인물로도 기록돼 있다. 2009년...',
    'https://www.globale.co.kr/news/articleView.html?idxno=39077',
    'globale.co.kr',
    TIMESTAMPTZ '2026-06-30T05:50:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000070', '삼양홀딩스' FROM news.articles a WHERE a.url = 'https://www.globale.co.kr/news/articleView.html?idxno=39077'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

COMMIT;

-- Generated by naver_news_fetch.py
-- query='하이트진로'  count=5  generated_at=2026-07-08T21:52:16.894942+00:00
BEGIN;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '하이트진로 작년 Scope 1·2 전년비 3.3%↓..Scope 3는 미공개',
    '포쓰저널 이남주 기자 하이트진로 ''지속가능경영보고서 2026'' 표지 캡쳐 하이트진로가 지난해 온실가스와 에너지, 용수, 폐기물 등 주요 환경지표를 전반적으로 줄인 것으로 나타났다. 반면 플라스틱...',
    'http://www.4th.kr/news/articleView.html?idxno=2114460',
    '4th.kr',
    TIMESTAMPTZ '2026-07-08T09:28:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000080', '하이트진로' FROM news.articles a WHERE a.url = 'http://www.4th.kr/news/articleView.html?idxno=2114460'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '''K-푸드'' 수출 호조…실적은 ''상반'', 식품 ''맑음''·주류 ''흐림''',
    '에프앤가이드에 따르면 롯데칠성음료의 올해 2분기 영업이익은 622억원으로 전년 동기 대비 0.3%, 하이트진로는 601억원으로 6.7% 감소할 것으로 전망된다. 이에 롯데칠성과 하이트진로는 가격 인상과 해외 시장 확대...',
    'http://www.srtimes.kr/news/articleView.html?idxno=207069',
    'srtimes.kr',
    TIMESTAMPTZ '2026-07-08T07:34:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000080', '하이트진로' FROM news.articles a WHERE a.url = 'http://www.srtimes.kr/news/articleView.html?idxno=207069'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '[유통가 상반기 돌아보니] ⑨술잔은 비고 위기감은 차오르고...주류계 ''...',
    '하이트진로는 올해 1분기 매출과 영업이익이 모두 감소하며 소비 위축의 영향을 고스란히 받았다. 핵심 사업인 소주와 맥주가 모두 역성장을 기록했고 생수 사업이 증가세를 보이며 일부 손실을 메우는 역할을 했다....',
    'https://www.straightnews.co.kr/news/articleView.html?idxno=306652',
    'straightnews.co.kr',
    TIMESTAMPTZ '2026-07-08T07:28:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000080', '하이트진로' FROM news.articles a WHERE a.url = 'https://www.straightnews.co.kr/news/articleView.html?idxno=306652'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '실적 주춤 하이트진로, BTS·신제품 효과 볼까',
    '하이트진로가 좀처럼 살아나지 않는 실적을 끌어올리기 위해 승부수를 던지고 있다. 국내 주류 시장 성장세가 둔화한 가운데 해외 시장 공략과 신제품 확대를 동시에 추진하며 실적 회복의 돌파구를 모색하는...',
    'https://zdnet.co.kr/view/?no=20260708154822',
    'zdnet.co.kr',
    TIMESTAMPTZ '2026-07-08T07:20:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000080', '하이트진로' FROM news.articles a WHERE a.url = 'https://zdnet.co.kr/view/?no=20260708154822'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

INSERT INTO news.articles (title, content_summary, url, source, published_at) VALUES (
    '주류 출고량 10년 새 21% ... 무알코올 키우는 하이트진로·오비맥주·롯...',
    '업계는 술자리 분위기는 즐기되 알코올 부담은 낮추려는 소비자를 겨냥해 새로운 활로를 찾고 있다.8일 하이트진로음료에 따르면 무알코올 맥주맛 음료 테라 제로는 출시 100일 만에 누적 판매량 400만캔을 돌파했다....',
    'https://vop.co.kr/A00001695738.html',
    'vop.co.kr',
    TIMESTAMPTZ '2026-07-08T06:56:00+00:00'
) ON CONFLICT (url) DO NOTHING;
INSERT INTO news.article_stock_mappings (article_id, stock_code, matched_keyword)
    SELECT a.id, '000080', '하이트진로' FROM news.articles a WHERE a.url = 'https://vop.co.kr/A00001695738.html'
    ON CONFLICT (article_id, stock_code) DO NOTHING;

COMMIT;

